server:
  port: 8080

spring:
  application:
    name: edu-service

  datasource:
    url: ${EDU_DATASOURCE_URL}
    username: ${EDU_DATASOURCE_USERNAME}
    password: ${EDU_DATASOURCE_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always