server:
  port: 8080
  servlet:
    context-path: /edu

spring:
  application:
    name: edu-service
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always